# SENSITIVE CONFIGURATION - DO NOT COMMIT WITHOUT FILTERING
# Updated: 2026-01-31

# GATES
GATE_1_KEY = "AIzaSyDIv2A7-Zl7tAwSfcykm4CFB_wzpzCCSfI"
GATE_2_BASE_KEY = "AIzaSyAZtu_A9L6eie6exQNrUqULfDi1UV_hSTI"
GATE_2_REINFORCED_KEY = "AIzaSyBAOjvpDVebzcHm22G-ALrpKMj9hU2RiVs"

# MAIN ANALYST (Switched to Developer Key due to expiry)
ANALYST_KEY = "AIzaSyBDYE6ZZ6xE4PEyG_x6I4lN9j68Gj6mCYI"

# OTHER
JOBS_KEY = "AIzaSyCCNzjiSCTlW5CA1JXBs0lJm8eEHfqyKwI"
DEV_ANALYST_KEY = "AIzaSyBDYE6ZZ6xE4PEyG_x6I4lN9j68Gj6mCYI"
