# API Configuration Template
# Copy this file to api_config.py and add your real keys
# DO NOT commit api_config.py with real keys

# GATES
GATE_1_KEY = "YOUR_GATE_1_KEY_HERE"
GATE_2_BASE_KEY = "YOUR_GATE_2_BASE_KEY_HERE"
GATE_2_REINFORCED_KEY = "YOUR_GATE_2_REINFORCED_KEY_HERE"

# MAIN ANALYST
ANALYST_KEY = "YOUR_ANALYST_KEY_HERE"

# OTHER
JOBS_KEY = "YOUR_JOBS_KEY_HERE"
DEV_ANALYST_KEY = "YOUR_DEV_ANALYST_KEY_HERE"
